name: MiniBosses
version: '${project.version}'
main: net.scaredrabbit.minibosses.Main
author: ScaredRabbitNL
api-version: '1.20'
commands:
   minibosses:
     description: "Main command for the plugin"
     aliases: mb
